# Cloudflare 名前付きトンネル（固定 URL）の初回セットアップ
# 前提: 無料 Cloudflare アカウント + Cloudflare に追加済みのドメイン

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path $PSScriptRoot -Parent
Set-Location $ProjectRoot

if (-not $env:TRANSCRIPT_RELAY_SECRET) {
  $env:TRANSCRIPT_RELAY_SECRET = "vidnote-relay-2026"
}

function Get-CloudflaredPath {
  $cmd = Get-Command cloudflared -ErrorAction SilentlyContinue
  if ($cmd) { return $cmd.Source }
  $wingetPath = Join-Path $env:LOCALAPPDATA `
    "Microsoft\WinGet\Packages\Cloudflare.cloudflared_Microsoft.Winget.Source_8wekyb3d8bbwe\cloudflared.exe"
  if (Test-Path $wingetPath) { return $wingetPath }
  throw "cloudflared not found. Run: winget install Cloudflare.cloudflared"
}

function Pause-BeforeExit {
  param([int]$Code = 0)
  Write-Host ""
  Write-Host "Press Enter to close..."
  Read-Host | Out-Null
  exit $Code
}

Write-Host ""
Write-Host "=== VidNote 固定 URL トンネル セットアップ ===" -ForegroundColor Cyan
Write-Host ""
Write-Host "必要なもの:"
Write-Host "  1. 無料 Cloudflare アカウント (https://dash.cloudflare.com/sign-up)"
Write-Host "  2. Cloudflare に追加済みのドメイン (例: example.com)"
Write-Host ""

$hostname = Read-Host "固定ホスト名を入力 (例: relay.example.com)"
$hostname = $hostname.Trim()
if ($hostname -notmatch '^[a-z0-9.-]+\.[a-z]{2,}$') {
  Write-Host "ホスト名の形式が不正です: $hostname" -ForegroundColor Red
  Pause-BeforeExit 1
}

$tunnelName = "vidnote-relay"
$Cloudflared = Get-CloudflaredPath
$configDir = Join-Path $ProjectRoot "cloudflared"
$configPath = Join-Path $configDir "config.yml"
New-Item -ItemType Directory -Force -Path $configDir | Out-Null

Write-Host ""
Write-Host "[1/5] Cloudflare にログイン (ブラウザが開きます)..."
& $Cloudflared tunnel login
if ($LASTEXITCODE -ne 0) { throw "cloudflared tunnel login failed" }

Write-Host ""
Write-Host "[2/5] トンネル作成: $tunnelName"
$createOut = & $Cloudflared tunnel create $tunnelName 2>&1 | Out-String
Write-Host $createOut

$credDir = Join-Path $env:USERPROFILE ".cloudflared"
$credFile = Get-ChildItem -Path $credDir -Filter "*.json" -ErrorAction SilentlyContinue |
  Sort-Object LastWriteTime -Descending |
  Select-Object -First 1
if (-not $credFile) {
  throw "credentials JSON not found in $credDir"
}

Write-Host ""
Write-Host "[3/5] DNS ルート: $hostname"
& $Cloudflared tunnel route dns $tunnelName $hostname
if ($LASTEXITCODE -ne 0) { throw "tunnel route dns failed" }

$fixedUrl = "https://$hostname"
$configYaml = @"
# Generated by setup-named-tunnel.ps1
tunnel: $tunnelName
credentials-file: $($credFile.FullName -replace '\\', '/')

ingress:
  - hostname: $hostname
    service: http://127.0.0.1:8787
  - service: http_status:404
"@

Set-Content -Path $configPath -Value $configYaml -Encoding UTF8
Write-Host ""
Write-Host "[4/5] config.yml を保存: $configPath"

Write-Host ""
Write-Host "[5/5] Vercel に固定 URL を設定..."
Push-Location $ProjectRoot
try {
  & npx vercel env rm TRANSCRIPT_RELAY_URL production --yes 2>&1 | Out-Null
  & npx vercel env add TRANSCRIPT_RELAY_URL production --value $fixedUrl --yes --force --no-sensitive 2>&1 | Out-Null
  if ($LASTEXITCODE -ne 0) {
    Write-Host "  Vercel 手動設定: TRANSCRIPT_RELAY_URL=$fixedUrl" -ForegroundColor Yellow
  } else {
    Write-Host "  Vercel TRANSCRIPT_RELAY_URL = $fixedUrl" -ForegroundColor Green
    Write-Host "  Redeploying production (1回のみ)..."
    & npx vercel deploy --prod --yes 2>&1 | Out-Null
  }
} finally {
  Pop-Location
}

Write-Host ""
Write-Host "=== セットアップ完了 ===" -ForegroundColor Green
Write-Host "固定 URL: $fixedUrl"
Write-Host ""
Write-Host "次回からは scripts/start-named-relay-tunnel.ps1 を起動してください。"
Write-Host "（PC 再起動のたびに URL 変更・Vercel 再設定は不要です）"
Write-Host ""
Pause-BeforeExit 0
